import { useEffect, useState } from "react";
import styles from "./ExampleProfile.module.scss";
import LinkButton from "./LinkButton";
import axios from "axios";

export default function ExampleProfile() {
  const [loading, setLoading] = useState<boolean>(true);
  const [avatar, setAvatar] = useState<string>();
  const [name, setName] = useState<string>();

  useEffect(() => {
    axios
      .get("https://randomuser.me/api")
      .then((res) => {
        const result = res.data.results[0];
        setName(result.name.first + " " + result.name.last);
        setAvatar(result.picture.large);
        setLoading(false);
      })
      .catch((err) => {
        console.log(err);
        setName("Willie Woods");
        setAvatar("https://randomuser.me/api/portraits/men/52.jpg");
        setLoading(false);
      });
  }, []);

  return (
    <main className={styles.wrapper}>
      {!loading && (
        <>
          <img src={avatar} alt="Avatar" className="avatar" />
          <span className={styles.name}>{name}</span>
          <span className={styles.bio}>
            Hello! My name is {name}, and I use Linkship.
          </span>
          <div className={styles.links}>
            <LinkButton icon="youtube" color="#F00">
              YouTube
            </LinkButton>
            <LinkButton icon="twitter" color="#1DA1F2">
              Twitter
            </LinkButton>
            <LinkButton icon="twitch" color="#6441A5">
              Twitch
            </LinkButton>
            <LinkButton icon="discord" color="#5865F2">
              Discord
            </LinkButton>
          </div>
        </>
      )}
      <span className={styles.copyright}>
        Example generated by{" "}
        <a href="https://randomuser.me">
          <u>randomuser.me</u>
        </a>
      </span>
    </main>
  );
}
